---
# tasks file for dahdi (runs before installing/compiling asterisk)

- name: Remove existing DAHDI source dir
  file: "path={{ iasterisk_dahdi_srcdir }} state=absent"

- name: Create DAHDI source dir
  file: "path={{ iasterisk_dahdi_srcdir }} state=directory"

- name: Download and extract DAHDi source
  unarchive: "src={{ iasterisk_url_dahdi }} dest={{ iasterisk_dahdi_srcdir }} remote_src=yes extra_opts=--strip-components=1"

- name: "Build DAHDI from tarball"
  command: "{{ item }} chdir={{ iasterisk_dahdi_srcdir }}"
  with_items:
    - make all
    - make install
    - make config